# Generated by Django 2.1.5 on 2019-01-13 19:19

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=account.models.PhoneField(max_length=20, unique=True, verbose_name='phone number'),
        ),
    ]
