# Generated by Django 2.1.5 on 2019-01-15 12:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190115_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('register_until', models.DateTimeField(default=datetime.datetime(2019, 1, 15, 13, 3, 21, 549177, tzinfo=utc))),
                ('register_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
