# Generated by Django 2.1.5 on 2019-02-15 10:34

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190215_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=account.models.PhoneField(max_length=20, unique=True, verbose_name='전화번호'),
        ),
    ]
