# Generated by Django 2.1.5 on 2019-02-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_question_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Applicant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Question')),
            ],
        ),
    ]
