# Generated by Django 2.1.5 on 2019-02-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_applicantapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
