# Generated by Django 2.1.5 on 2019-02-21 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_applicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
