# Generated by Django 2.1.5 on 2019-03-06 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_auto_20190306_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Application'),
        ),
    ]
