# Generated by Django 2.1.5 on 2019-03-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_auto_20190306_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='user',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
