# Generated by Django 2.1.5 on 2019-03-06 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_auto_20190306_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.ApplicantApplication')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Evaluation')),
            ],
        ),
        migrations.RemoveField(
            model_name='answerevaluation',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerevaluation',
            name='evaluation',
        ),
        migrations.DeleteModel(
            name='AnswerEvaluation',
        ),
    ]
