# Generated by Django 2.1.5 on 2019-03-06 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0012_auto_20190306_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='applicationevaluation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerevaluation',
            name='application_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.ApplicationEvaluation'),
        ),
    ]
