# Generated by Django 2.1.5 on 2019-03-06 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_auto_20190306_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('application_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.ApplicationEvaluation')),
            ],
        ),
    ]
