# Generated by Django 2.1.5 on 2019-03-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_auto_20190308_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='links',
            field=models.TextField(default=''),
        ),
    ]
