# Generated by Django 2.1.5 on 2019-03-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_applicant_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='portfolio',
            field=models.URLField(default=''),
        ),
    ]
