# Generated by Django 2.1.5 on 2019-03-09 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_applicant_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Applicant')),
            ],
        ),
        migrations.AddField(
            model_name='applicantapplication',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
