# Generated by Django 2.1.5 on 2019-03-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_auto_20190309_2200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterView',
            new_name='Interviewee',
        ),
        migrations.AlterModelOptions(
            name='interviewee',
            options={'ordering': ('date_time',)},
        ),
    ]
