# Generated by Django 2.1.5 on 2019-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisg_calendar', '0003_absent_exemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='absent',
            name='counted',
            field=models.BooleanField(default=False),
        ),
    ]
