# Generated by Django 2.1.5 on 2019-03-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisg_calendar', '0004_absent_counted'),
    ]

    operations = [
        migrations.AddField(
            model_name='absent',
            name='absent_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '결석'), (2, '지각')], default=1),
        ),
    ]
