# Generated by Django 2.1.5 on 2019-03-18 08:37

import LikeLion.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisg_calendar', '0005_absent_absent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.FileField(blank=True, upload_to=LikeLion.utils.custom_path),
        ),
    ]
