# Generated by Django 2.1.5 on 2019-03-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HTML'), (2, 'CSS'), (3, 'Python')], default=1),
            preserve_default=False,
        ),
    ]
