# Generated by Django 2.1.5 on 2019-03-20 03:07

import LikeLion.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20190320_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='materials',
            field=models.FileField(blank=True, upload_to=LikeLion.utils.custom_path),
        ),
    ]
