# Generated by Django 2.1.5 on 2019-03-20 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignment_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitImage',
            fields=[
                ('submit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assignment.Submit')),
            ],
            bases=('assignment.submit',),
        ),
        migrations.AlterField(
            model_name='submit',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HTML'), (2, 'CSS'), (3, 'Python'), (4, '일반 텍스트'), (5, '링크')]),
        ),
    ]
