# Generated by Django 2.1.5 on 2019-03-20 04:50

import LikeLion.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20190320_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitimage',
            name='image',
            field=models.ImageField(default=None, upload_to=LikeLion.utils.custom_path),
            preserve_default=False,
        ),
    ]
