# Generated by Django 2.1.5 on 2019-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20190320_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HTML'), (2, 'CSS'), (3, 'Python'), (4, '일반 텍스트'), (5, '링크')]),
        ),
    ]
