# Generated by Django 2.1.5 on 2019-03-27 07:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20190320_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmitInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.PositiveSmallIntegerField(choices=[(1, 'HTML'), (2, 'CSS'), (3, 'Python'), (4, '일반 텍스트'), (5, '링크')])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
            ],
        ),
    ]
