# Generated by Django 2.1.5 on 2019-03-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_assignmentsubmitinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmitinformation',
            name='field_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
