# Generated by Django 2.1.5 on 2019-03-27 13:17

import LikeLion.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_auto_20190327_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmitTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=LikeLion.utils.custom_path)),
                ('link', models.URLField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignmentsubmitinformation',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmitInformation',
        ),
    ]
