# Generated by Django 2.1.5 on 2019-03-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_assignmentsubmittotal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmittotal',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
