# Generated by Django 2.1.5 on 2019-03-30 01:35

import LikeLion.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_assignmentsubmittotal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmittotal',
            name='image',
            field=models.ImageField(blank=True, upload_to=LikeLion.utils.custom_path),
        ),
    ]
